### ISSUE TITLE
Apothecary water input

### ISSUE THREAD

**Issue by NanJack1998** [MelanX/botanical-machinery#41]
may i ask how i can push water into the Apothecary?

i'v try Fluid System/Mekanism and some other mod which has pipe to tranfer fluid,but none of them successfully make water into the Apothecary.

all the mod are latest version and in a 1.16 game

**Comment by MelanX** [comment]
Fluid pipes should work. I personally used a fluid exporter from Refined Storage 🤔

**Comment by NanJack1998** [comment]
well,will have a try with ae/rs/xnet pipe

**Comment by NanJack1998** [comment]
> Fluid pipes should work. I personally used a fluid exporter from Refined Storage 🤔

hello,i've try a while with ae/rs/xnet pipe ,but none of them can work on the Apothecary,maybe i've got too many mods in my modpack 
can i get a photo showing me how you solve the Apothecary water input?

**Comment by MelanX** [comment]
https://www.reddit.com/r/feedthebeast/comments/iifvkh/botanical_machinery_a_new_botania_addon/
See in the second video

**Comment by NanJack1998** [comment]
https://youtu.be/sjXrHkQV7RE
this my third try after watching the video,it still not working
and here is my modlist:https://paste.ubuntu.com/p/X2J8gHWNQs/

**Comment by noeppi-noeppi** [comment]
Not reproducible. Seems like it's an incompatability. Could you maybe find out which mod causes this to happen by removing one after another and see when it starts working? And if does not work when you removed all of the mods could we get your minecraft log?

**Comment by NanJack1998** [comment]
ok,i will have a try,but it may take a long while cause i only have not much time to do this,but i will try!

**Comment by NanJack1998** [comment]
> Not reproducible. Seems like it's an incompatability. Could you maybe find out which mod causes this to happen by removing one after another and see when it starts working? And if does not work when you removed all of the mods could we get your minecraft log?

i solve the problem in a simple way ,the apothecary only accept water when there's at least one item(seeds or something else) in it ,it's not about mod incompatability.

**Comment by NanJack1998** [comment]
and it's also a weird thing is the real water contain isn't correctly display ,if the water input speed isn't large enouth ,it only display the current water contain at the moment i add one more item(from 0 to inf),and it stop increase the water contain number,it seems a update due to the change of the items

**Comment by MelanX** [comment]
That sounds really strange and I never saw this behaviour before 🤔

**Comment by MelanX** [comment]
Can you provide a video where that happens? I don't know how to reproduce.

**Comment by NanJack1998** [comment]
well,in the latest version,this has been fixed,thanks
