### ISSUE TITLE
Error loading 0.3.2

### ISSUE THREAD

**Issue by GnomTocha** [MelanX/botanical-machinery#42]
**Versions**

Minecraft: 1.16.4
Forge: 35.1.28
Botania: Botania-1.16.4-410
Botanical Machinery: botanicalmachinery-1.16.4-0.3.2
Modpack: 

I use my pack of mods
**Describe the bug**

The game does not start. I threw the screen. With version botanicalmachinery-1.16.4-0.3.1, there are no problems at launch.
**How to reproduce**

1. Start the game and wait.
2. Start the game and wait.
3. Start the game and wait.

**Expected behavior**

It will show an error at startup. Watch the screen.
**Screenshots**

![image](https://user-images.githubusercontent.com/75666317/104214467-8626cb80-5448-11eb-8b6b-4b586e23e464.png)
[debug.log](https://github.com/MelanX/botanical-machinery/files/5797682/debug.log)
[latest.log](https://github.com/MelanX/botanical-machinery/files/5797684/latest.log)

**Comment by MelanX** [comment]
You need to update LibX to at least version 1.0.10
