### ISSUE TITLE
alfheim market error

### ISSUE THREAD

**Issue by Jly4** [MelanX/botanical-machinery#49]
Minecraft: 1.16.5
Forge: 1.16.5 - 36.2.4
Botania: 1.16.5-419
Botanical Machinery: 1.16.4-0.4.4
LibX: 1.16.3-1.0.76
Modpack: ATM 6

When exchanging diamonds, a regular diamond is obtained instead of a dragon stone

<img width="475" alt="Botania" src="https://user-images.githubusercontent.com/65804380/134164342-42a15513-1f45-4f8d-80d9-cc6351affcb7.png">

**Comment by MelanX** [comment]
Dragonstones are made of Mana Diamonds. Diamonds don't have a recipe in the Alfheim Market, so it just returns the original item.
