### ISSUE TITLE
There's no chapter of Botanical Machinery in Lexica Botania.

### ISSUE THREAD

**Issue by obscure-man** [MelanX/botanical-machinery#58]
### Minecraft version

1.18.2

### Botanical Machinery version

1.18.2-1.0.2

### LibX version

1.18.2-3.2.19

### Botania version

1.18.2-435

### Forge version

40.1.86

### The latest.log file

https://pastebin.com/KFCNgMr2

### Issue description

I don't know it's a bug or the chapter haven't done. There's no chapter of Botanical Machinery in Lexica Botania.

**Comment by MelanX** [comment]
Fixed it in [1.19 before](https://github.com/MelanX/botanical-machinery/commit/47e165fa6f8a08dbd15c2476184226e4ff779878), cherry-picked the fix for [1.18 now](https://github.com/MelanX/botanical-machinery/commit/ff8b1aad9126faeb5d57f39ef583f60bfa472583).
