### ISSUE TITLE
Need help for "Mana Battery"

### ISSUE THREAD

**Issue by Frenqy** [MelanX/botanical-machinery#59]
### Describe your idea

There's not enough infomation for mana battery so that I don't know what can it do.

Q1: how can i input mana to battery? spreader? spark? or only item with mana?

Q2: can i replace mana pool array with mana battery? i want to generate mana then store mana in battery other than mana pool, and i also want the battery provide mana to other machine directly

thanks

**Comment by MelanX** [comment]
A1: Yes, with spreader, spark, as well as an item.

A2: Yes, this should work. It’s like a pool which outputs mana to its neighbor blocks.
