### ISSUE TITLE
[1.19.2] Allow More Than Seeds in Mech Apoth

### ISSUE THREAD

**Issue by ScoutTheSaneless** [MelanX/botanical-machinery#61]
### Describe your idea

I'm currently using KubeJS to add recipes using Botania that use different catalysts than seeds, but the mechanical petal apothecary only accepts seeds as the catalyst, which breaks my recipes. If it's at all possible, I would like a fix that addresses this!

**Comment by MelanX** [comment]
Add your catalysts to the item tag `#botanicalmachinery:mechanical_apothecary_catalysts` (if you still need it).
