### ISSUE TITLE
[1.16] Crash when mining the mana battery

### ISSUE THREAD

**Issue by jinkhya** [MelanX/botanical-machinery#63]
### Minecraft version

1.16

### Botanical Machinery version

1.16.4-0.4.6.jar

### LibX version

1.16.3-1.0.76

### Botania version

1.16.5-420.3

### Forge version

36.2.39

### The latest.log file

https://gist.github.com/jinkhya/3a33c472965b009d484b6197790daeb6

### Issue description

Hello
A player on my server mined the mana battery and it crashed. 
When I filled out this form there was no option for 1.16. Does that mean there's no support for 1.16 anymore? 
Best regards,
Jin

**Comment by MelanX** [comment]
Hi. I don't know why this crash happened. I mean... I know the problem and fixed it, but I don't know why this was the case. The game wanted to get some info from the battery after the battery was mined. I don't know, it's fixed anyway.
And yes, 1.16 isn't supported anymore. But if it's easy like this, why not :)

**Comment by jinkhya** [comment]
Thank you, I appreciate that :)
Might have been a one time thing but it's always nice to have it fixed :)
