### ISSUE TITLE
Alfheim Market constant drain

### ISSUE THREAD

**Issue by Rainmaker709** [MelanX/botanical-machinery#68]
### Minecraft version

1.19.2

### Botanical Machinery version

BotanicalMachinery-1.19.2-2.0.4

### LibX version

LibX-1.19.2-4.2.8

### Botania version

Botania-1.19.2-440-FORGE

### Forge version

43.3.8

### The latest.log file

No

### Issue description

Market has a constant drain of mana. This is not the default behavior of the normal Portal and I don't see any option in the Config Json so I am unsure if this is intended. Also the drain is not unsustainable but by no means a trivial amount.

As the portal is pretty trivial to automate normally, if this is intended then it makes the Market not worth bothering with IMO.

I am playing FTB Skies Expert, Providing mana with a Spark.

### Steps to reproduce

Make Market.
Give spark.
Watch pool drain forever.

**Comment by MelanX** [comment]
I'm sorry, I tested it: It stays at full capacity for me. Attaching a spark didn't change it. I also placed an empty Mana Battery a few blocks away with a dominant spark, still no draining. Could you record that? Maybe it's something else which is draining the mana.

**Comment by Rainmaker709** [comment]
![2024-04-22_10 13 32](https://github.com/MelanX/botanical-machinery/assets/67436454/89ff460f-0bb8-4a84-be48-a688cbae5898)

Here is a picture of my setup. After further testing I determined that the culprit was the Mana Spreader to the right of the Market.

Would be nice if it didn't do that but wouldn't call it a bug so much as unexpected behavior. Don't know if you could/want to change it. Should have done more testing before submitting. Apologizes.
