### ISSUE TITLE
1.20.1 | The mechanical daisy refuses to take resources from the funnel.

### ISSUE THREAD

**Issue by DesiRe234** [MelanX/botanical-machinery#70]
### Minecraft version

1.20.1

### Botanical Machinery version

1.20.1-3.0.2

### LibX version

1.20.1-5.0.5

### Botania version

1.20.1-444-FORGE-SNAPSHOT

### Forge version

47.2.1

### Issue description

The mechanical daisy refuses to take resources from the funnel.

## Tags:
'minecraft:hopper', 
'botanicalmachinery:mechanical_daisy'

**Comment by MelanX** [comment]
Works for me, see video:
https://github.com/MelanX/botanical-machinery/assets/26039509/13a1f8d6-151f-403c-84a9-0a796ca2c593
