### ISSUE TITLE
Japanese translation is not applied

### ISSUE THREAD

**Issue by EndilCrafter** [MelanX/botanical-machinery#76]
### Minecraft version

None

### Botanical Machinery version

1.20.1-3.0.5

### LibX version

latest

### Botania version

latest

### Forge version

latest

### The latest.log file

no

### Issue description

I pulled translation request and it merged, but latest version does not include it.

**Comment by MelanX** [comment]
I'm so sorry, that's totally my fault. I forgot to pull the changes from GitHub before building the file. That happened because the releasing workflow still doesn't work and needs to be done manually. Will release a version with Japanese in the next few minutes.
